### ISSUE TITLE
Can't locate JSON.pm in @INC (you may need to install the JSON module)

### ISSUE THREAD

**Issue by nephew92** [fangq/covid19#1]
`gbff2json.pl` uses a non-builtin module and there's no instructions at readme file how to install them. I've tried 
```
[sudo] cpan JSON
```
but I got the same error.

**Comment by fangq** [comment]
@nephew92, I used two perl modules, JSON and Tie::IxHash

https://github.com/fangq/gbff2json/blob/master/src/gbff2json.pl#L16-L17

depends on what OS you are using, on Ubuntu/Debian, you need to install these additional packages
```
sudo apt-get install libtie-ixhash-perl libjson-perl
```
you should also be able to install both using cpan.

For JSON, a replacement is `JSON::PP`, which is now in the core. But still people need `Tie::IxHash` to keep the output data in orders.

I will add these instructions to the README. If cpan does not work on your machine, perhaps you want to see the output and whether there was an installation error.
