### ISSUE TITLE
Gbff file with multi "LOCUS", extract only the first one. 

### ISSUE THREAD

**Issue by lisboazootec** [fangq/covid19#2]
Bgff file with multi "LOCUS", extract only the first one. 
Example file on the link (ftp://ftp.ncbi.nlm.nih.gov/refseq/release/bacteria/bacteria.1.genomic.gbff.gz). 
How to get around this problem? 
I need the .json file to integrate into a pipeline. Thanks!

**Comment by fangq** [comment]
@lisboazootec, should be fixed by the above commit. it took about 1 min 51 sec to convert the gbff file on my desktop, output is a 410MB json file. Let me know if you see any problem with this.
